sonar.projectKey=lab-inventory-service
sonar.projectName=lab-inventory-service
sonar.sources=src/main
sonar.java.binaries=target/classes
sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/*.spec.ts
sonar.qualitygate.wait=true
# SonarCloud
sonar.organization=kanduc